#import <CoreFoundation/CoreFoundation.h>
#import <CoreGraphics/CGGeometry.h>
#import <CoreText/CoreTextExport.h>
#import <CoreText/CTFontTraits.h>

CORETEXT_EXPORT const CFStringRef kCTFontURLAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontNameAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontDisplayNameAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontFamilyNameAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontStyleNameAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontTraitsAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontVariationAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontVariationAxesAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontSizeAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontMatrixAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontCascadeListAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontCharacterSetAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontLanguagesAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontBaselineAdjustAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontMacintoshEncodingsAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontFeaturesAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontFeatureSettingsAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontFixedAdvanceAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontOrientationAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontEnabledAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontFormatAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontRegistrationScopeAttribute;
CORETEXT_EXPORT const CFStringRef kCTFontPriorityAttribute;

CF_IMPLICIT_BRIDGING_ENABLED

typedef struct __CTFontDescriptor* CTFontDescriptorRef;

typedef enum CTFontOrientation : uint32_t {
  kCTFontOrientationDefault = 0,
  kCTFontDefaultOrientation = 0, // Deprecated
  kCTFontOrientationHorizontal = 1,
  kCTFontHorizontalOrientation = 1, // Deprecated
  kCTFontOrientationVertical = 2,
  kCTFontVerticalOrientation = 2, // Deprecated
} CTFontOrientation;

CORETEXT_EXPORT CFTypeRef CTFontDescriptorCopyAttribute(CTFontDescriptorRef descriptor, CFStringRef attribute);

CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateWithAttributes(CFDictionaryRef attributes);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateWithNameAndSize(CFStringRef name, CGFloat size);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateCopyWithAttributes(CTFontDescriptorRef original, CFDictionaryRef attributes);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateCopyWithFamily(CTFontDescriptorRef original, CFStringRef family);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateCopyWithSymbolicTraits(CTFontDescriptorRef original, CTFontSymbolicTraits value, CTFontSymbolicTraits mask);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateCopyWithVariation(CTFontDescriptorRef original, CFNumberRef variationIdentifier, CGFloat variationValue);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateCopyWithFeature(CTFontDescriptorRef original, CFNumberRef featureTypeIdentifier, CFNumberRef featureSelectorIdentifier);
CORETEXT_EXPORT CFDictionaryRef CTFontDescriptorCopyAttributes(CTFontDescriptorRef descriptor);
CORETEXT_EXPORT CFTypeRef CTFontDescriptorCopyLocalizedAttribute(CTFontDescriptorRef descriptor, CFStringRef attribute, CFStringRef *language);
CORETEXT_EXPORT CTFontDescriptorRef CTFontDescriptorCreateMatchingFontDescriptor(CTFontDescriptorRef descriptor, CFSetRef mandatoryAttributes);
CORETEXT_EXPORT CFArrayRef CTFontDescriptorCreateMatchingFontDescriptors(CTFontDescriptorRef descriptor, CFSetRef mandatoryAttributes);
CORETEXT_EXPORT CFTypeID CTFontDescriptorGetTypeID(void);

CF_IMPLICIT_BRIDGING_DISABLED
